version: '3.8'

services:
  web-scraper-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_scraper_microservice
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped
